### ISSUE TITLE
What is the python version, mayavi version and vtk version you are using in this project?

### ISSUE THREAD

**Issue by WXONE** [wmvanvliet/scns#1]
Hi，Hi, I ran this project on my own computer, and when I run the render file, it reports the error "traits.trait_errors.TraitError: The 'outline_color' trait of an OrientationMarkerWidget instance must be a tuple of the form: (0.0 <= a floating point number <= 1.0, 0.0 <= a floating point number <= 1.0, 0.0 <= a floating point number <= 1.0), but a value of '_000001ed0be99bb0_p_void' <class 'str'> was specified.", my mayavi version is 4.7.2, vtk version is 8.1.2, python version is 3.6, what version are you using?

**Comment by wmvanvliet** [comment]
Python = 3.9.16
Mayavi = 4.8.1
VTK = 9.1.0

**Comment by sneccc** [comment]
@wmvanvliet btw what torch version did u used?
```raceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "P:\python\visualizations\scns\visualizations\multilayer_perceptron\mnist.py", line 97, in <module>
    train(args, model, device, train_loader, optimizer, epoch)
  File "P:\python\visualizations\scns\visualizations\multilayer_perceptron\mnist.py", line 13, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "P:\python\visualizations\scns\venvv\lib\site-packages\torch\utils\data\dataloader.py", line 439, in __iter__
    return self._get_iterator()
  File "P:\python\visualizations\scns\venvv\lib\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "P:\python\visualizations\scns\venvv\lib\site-packages\torch\utils\data\dataloader.py", line 1040, in __init__
    w.start()
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "P:\python\visualizations\scns\venvv\lib\site-packages\torch\utils\data\dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\queue.py", line 179, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "P:\python\visualizations\scns\visualizations\multilayer_perceptron\mnist.py", line 97, in <module>
    train(args, model, device, train_loader, optimizer, epoch)
  File "P:\python\visualizations\scns\visualizations\multilayer_perceptron\mnist.py", line 13, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "P:\python\visualizations\scns\venvv\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "P:\python\visualizations\scns\venvv\lib\site-packages\torch\utils\data\dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
  File "P:\python\visualizations\scns\venvv\lib\site-packages\torch\utils\data\dataloader.py", line 1285, in _get_data
    success, data = self._try_get_data()
  File "P:\python\visualizations\scns\venvv\lib\site-packages\torch\utils\data\dataloader.py", line 1146, in _try_get_data
    raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 26080) exited unexpectedly
```

**Comment by wmvanvliet** [comment]
that error looks like a problem with your pytorch installation. Do other datasets load properly? Try setting the number of workers to `0` to disable parallel processing and perhaps that sidesteps the problem you are having.
